### ISSUE TITLE
Allow editing and updating world mods.

### ISSUE THREAD

**Issue by SirLich** [Majic-Jungle/sapiens-mod-creation#10]
This is becoming a little bit of a blocker for us! In some cases, it's even encouraging people to write App mods rather than World mods because they are easier to toggle. 

`Note:` We are aware of a manual way to do it, involving manual file editing, and editing `config.XML`. 

Alongside adding/editing mods, a really important part will be updating mods. You can definitely expect future Sapiens updates to break mods, so it's going to be vital if users can update their world mods to the latest version on the steam workshop. 

I know this is a lot of work (UI, etc), but I believe it's an important part of a good modding solution for Sapiens.

**Comment by mjdave** [comment]
fixed b20
