### ISSUE TITLE
Expose `serverSapien.lua`

### ISSUE THREAD

**Issue by SirLich** [Majic-Jungle/sapiens-mod-creation#12]
In particular, I'm interested in values to adjust for my Vanilla Tweaks mod. 

In `serverSapiens.lua` you define a number of constants:

```lua
local pregnancySpeed = nil
local pregnancyDelaySpeed = nil
local infantAgeSpeed = nil
```

You later redefine these inside of `serverSapien:init`

```lua
    local dayLength = serverWorld:getDayLength()
    pregnancySpeed = (1.0 / (dayLength * sapienConstants.pregnancyDurationDays))
    infantAgeSpeed = (1.0 / (dayLength * sapienConstants.infantDurationDays))
    pregnancyDelaySpeed = (1.0 / (dayLength * sapienConstants.minTimeBetweenPregnancyDays))
```

My suggestion is at minimum make these local variables part of the exposed `serverSapiens` module, or potentially you could also think of defining a function like this:

```lua
function serverSapiens:getPregnancySpeed()
       return (1.0 / (dayLength * sapienConstants.pregnancyDurationDays))
end
```

This is shadowable and can therefor be used for whatever we need.

**Comment by mjdave** [comment]
fixed b21
