### ISSUE TITLE
Don't destroy existing description when updating mods in-game

### ISSUE THREAD

**Issue by SirLich** [Majic-Jungle/sapiens-mod-creation#14]
Once a mod is pushed to steam, the user will often update the description, title, tags, website links, etc. 

When updating from in-game, you shouldn't touch any of these fields (most annoyingly the description). Simply upload the code.

**Comment by SirLich** [comment]
Just to be clearer: The current behavior replaces the description field with the one in mod-info.lua, which is nearly always shorter/less complete/less formatted.

**Comment by mjdave** [comment]
Thanks for the report, I've added a checkbox when uploading in 0.3.6 so you can now configure this behavior.
