### ISSUE TITLE
Modify active mods from outside the game

### ISSUE THREAD

**Issue by DecDuck** [Majic-Jungle/sapiens-mod-creation#16]
I'm building a mod manager and would love to be able to automatically enable/disable mods without having to mess around with `data.mdb`. Can we have the enabled mods in the `config.xml`?

**Comment by SirLich** [comment]
To add more context: *World Mods* can be controlled via `config.xml`, but the same cannot be said for *App Mods*.

Besides the use-case of DecDuck, this is also desirable in case you create a game-crashing app mod. Although moving the files out is possible, having a human readable/writable format would be desirable.

**Comment by mjdave** [comment]
These are now stored in enabledAppMods.xml as of b21.
