### ISSUE TITLE
Allow reloading of C mods

### ISSUE THREAD

**Issue by suppergerrie2** [Majic-Jungle/sapiens-mod-creation#18]
The DLL file for a c mod is never released by the game, closing a world or unchecking the mod in the creation menu should unload the DLL so a full game restart is not needed to update the mod

**Comment by mjdave** [comment]
I did look into this, but I don't think there is a good solution engine-side. For now it's just something that will need to be managed in your development environment. You should be able to get your build tools to at least kill and relaunch the game when you do a build, so then in-game it is just a matter of hitting escape to skip the menu, and enter to continue.
