### ISSUE TITLE
Add a logger to C mods

### ISSUE THREAD

**Issue by suppergerrie2** [Majic-Jungle/sapiens-mod-creation#19]
Currently logging in c mods requires some hacks to write to a custom file, printf (and family) does not seem to print to any of the log files nor the console when opening sapiens with the console.

**Comment by mjdave** [comment]
There is a now new spLog() function added in 0.3.6 that will allow you to log in the same way that logging works elsewhere. This means that log messages using spLog will both print to the console, and to the per-thread log files in AppData/Roaming/majicjungle/sapiens. You will need to #include SPLog.h in the mod files to use it.

I don't know why exactly printf doesn't currently log to the console as well, but this seemed the best solution.
