### ISSUE TITLE
Expose build sequences in `buildable.lua`

### ISSUE THREAD

**Issue by SirLich** [Majic-Jungle/sapiens-mod-creation#27]
Build sequences are already exposed in `craftable.lua`. Also since they seem to share so much structure, you might actually consider refactoring them into a new file called like, `buildSequences.lua`.

This new file could contain all existing sequences from `craftable` and `buildable`. Having a single file for both types is a *bit* nice, because it means we have an obvious single source of truth to pull sequences from, and add more sequences. 

But just making those sequences non-local would be steller.

**Comment by mjdave** [comment]
Thanks, I'll leave the refactoring for now, but I've exposed the build sequences in 0.4.
