### ISSUE TITLE
Exposing `localPlayer.lua`

### ISSUE THREAD

**Issue by SirLich** [Majic-Jungle/sapiens-mod-creation#3]
This file has 140 local variables, and 40 local functions 🐙 

These are the fields I would like exposed, at a minimum. All fields actually *do something* when set directly, so they are good candidates:

 - `maxDistanceFromClosestSapien`
 - `maxPlayerHeight`
 - `speedIncreaseFactorAtMaxHeight`
 - `playerHeightMeters`

Thanks for looking into this :)

**Comment by mjdave** [comment]
I've exposed the first 3 in beta7, but playerHeightMeters probably isn't what you're wanting to change here, and could be a bit more tricky, so I'll leave that one for now. I also suspect we would need to expose a whole lot more to really allow good modding of this module. It might be better to shadow all of the main methods, basically copy and paste the whole file and make the changes you need that way.
