### ISSUE TITLE
Expose planManager.lua (see description)

### ISSUE THREAD

**Issue by SirLich** [Majic-Jungle/sapiens-mod-creation#37]
A few local functions that could be exposed:

1. updatePlansForFollowerOrOrderCountChange
2. getAndIncrementPlanID
3. setRequiredSkillForPlan
4. updateImpossibleStateForVert
5. getAndIncrementPrioritizedID
6. canCompleteIgnoringOrderLimit

**Comment by mjdave** [comment]
Exposed in 0.5.0.63
