### ISSUE TITLE
Request: Enhanced Character Support

### ISSUE THREAD

**Issue by gmirsky2** [Majic-Jungle/sapiens-mod-creation#38]
I'm currently in the process of developing a mod for the game that delves into linguistic nuances and historical contexts. To accurately portray these elements, I require the utilization of characters beyond the basic Latin alphabet. Ensuring support for these characters is crucial for maintaining the authenticity and depth of the mod.

However, I've encountered some challenges related to low-level font rendering and character encoding, issues that are typically managed by the underlying framework or system libraries.

Below is a non-comprehensive list of the characters I'm incorporating:

`h₁` `h₂` `h₃` `ḱ` `ǵ` `ǵʰ` `gʷ` `gʷʰ` `gʰ` `kʷ` `kʷʰ` `kʰ` `tʷ` `tʷʰ` `tʰ` 
`dʷ` `dʷʰ` `dʰ` `bʷ` `bʷʰ` `bʰ` `sʷ` `sʷʰ` `sʰ` `mʷ` `mʷʰ` `mʰ` `nʷ` `nʷʰ` `nʰ` 
`lʷ` `lʷʰ` `lʰ` `rʷ` `rʷʰ` `rʰ` `wʷ` `wʷʰ` `wʰ` `yʷ` `yʷʰ` `yʰ` 
`ʰ` `₂` `ǵ` `ú` `ó` `é` `₁` `ē` `ḗ` `₃` `l̥` `á` `ḱ` `ō` `n̥` `ʷ` `ā́`

For instance, some examples of my issue are as follows:

> **World Name:** `ḱléwós Dʰéǵʰōm` 
> Displays as: `léwós Dém`

> **World Name:** `wid DÊ°rÄÌks` 
> Displays as: `wid Drks`

> **World Name:** `bʰébʰrus`
Displays as: `bébrus`

![image](https://github.com/Sapiens-OSS/sapiens-modding-wiki/assets/93354167/6073452c-af99-41ab-92d4-4536a0d8ac5c)

To access these characters on Windows, follow these steps:

1. Press the **Windows key** and the **period key** simultaneously (Windows key + '.'). This will open the emoji/symbol panel.
2. Navigate to the **Latin category** or search for specific characters using their names or descriptions.

I strongly believe that integrating support for these characters into the game's text input system would significantly enrich the modding experience, enabling more diverse and accurate linguistic representations within the game.

Thank you for considering this request. Should you require any further clarification or assistance, please feel free to reach out.

**Comment by mjdave** [comment]
Hi there, I love what you are doing here, it looks amazing and I can't wait to see what you come up with.

Unfortunately, what you are requesting is no minor thing. Sapiens uses custom fonts, and these fonts are rendered to bitmaps for use in the game. This is a manual process, where I need to individually create characters and combinations of macrons etc, and it's a lot of work for me. It would take me multiple days of work to achieve what you are requesting.

It might be possible for you to create your own font bitmaps and get them working, but that's not something I can help with either at the moment given the work required to get 0.5 out the door.

I hope you can figure out a solution, good luck!

**Comment by gmirsky2** [comment]
> Hi there, I love what you are doing here, it looks amazing and I can't wait to see what you come up with.
> 
> Unfortunately, what you are requesting is no minor thing. Sapiens uses custom fonts, and these fonts are rendered to bitmaps for use in the game. This is a manual process, where I need to individually create characters and combinations of macrons etc, and it's a lot of work for me. It would take me multiple days of work to achieve what you are requesting.
> 
> It might be possible for you to create your own font bitmaps and get them working, but that's not something I can help with either at the moment given the work required to get 0.5 out the door.
> 
> I hope you can figure out a solution, good luck!

I fully understand. I didn't know if it was just a matter of changing from english to English, Latin-1, or something similar. Anyway, yes, focus on multiplayer; it's much more important. Thanks for replying.
