### ISSUE TITLE
Exposing `actionUI.lua`

### ISSUE THREAD

**Issue by SirLich** [Majic-Jungle/sapiens-mod-creation#4]
It's a little tricky for me to know what I need exposed, but at a minimum I need `selectedObjects` and `selectedVertInfos`. It's possible I can make this work with `actionUI:showObjects`... but I'm not sure.

Having `show` and `hide` and `init` exposed give me good lifecycle hooks. Just capturing the state is tricky.

The goal is to create a 'UI Slot' to the side of the Radial UI, which will be hidden/shown alongside the Radial UI, and receive context information so that buttons can be rendered based on the currently selected object. Mods will be able to register UI views which will be displayed in this slot.

Example uses for this slot:
 - Kill entity (cheat)
 - Remove object from world (cheat)
 - Duplicate selected entity (cheat)
 - Mark Sapien as tribe Leader (non-existent mod example)

![image](https://user-images.githubusercontent.com/18729296/167293359-43c0a5c0-b27c-4383-867c-c8a1330c9495.png)

**Comment by mjdave** [comment]
fixed b21
