### ISSUE TITLE
Exposing `mainMenu.lua`

### ISSUE THREAD

**Issue by SirLich** [Majic-Jungle/sapiens-mod-creation#5]
Most of the code is in a single, local function called `loadMainMenuView`, which is 500 lines of Lua. All variables are also local, such as the view, etc. 

In this case, I wanted to add a little decal or something into the menu, so I could easily check whether Hammerstone was enabled, but this was seemingly not possible.

**Comment by mjdave** [comment]
mainMenu.mainBanner is available, you should just be able to add your view there. But in beta 7 I have also exposed most of the rest of the UI, including all of the buttons, so you should be able to use them to help lay out things on the main menu.
