### ISSUE TITLE
Exposing `modelPlaceholder.lua`

### ISSUE THREAD

**Issue by SirLich** [Majic-Jungle/sapiens-mod-creation#6]
**Relevant mod**: https://github.com/SirLich/sapiens-plus-plus

This file doesn't exactly have very much exposed, including some critical methods like `addModel`. 

These are the things I think I need, but I may have missed some:
 - addModel
 - getModelIndexForStandardRemaps (?)
 - Remaps such as longBranchRemaps

Actually I'm sure I missed more. It's hard for me to know what's needed for exposure without the chance to create something based on it.

**Comment by mjdave** [comment]
fixed b20
