### ISSUE TITLE
Expose `terminal.lua`

### ISSUE THREAD

**Issue by SirLich** [Majic-Jungle/sapiens-mod-creation#7]
File is generally locked down. There are a few things I would like to adjust, without much capability to do so. 

I suggest unlocking the following:

1. Move pretty much all the local variables into the table. Stuff like `view` is good for customization, as is the history stuff, and definitely `luaPrompt`. 
2. `sendCommand`

**Comment by SirLich** [comment]
We actually started work on our own terminal, with autocomplete, and other stuff. So this is less important to me now.

**Comment by mjdave** [comment]
Thanks, I'll still expose it I think, might still come in handy.

**Comment by mjdave** [comment]
fixed b21
