### ISSUE TITLE
Expose `planHelper.lua`

### ISSUE THREAD

**Issue by SirLich** [Majic-Jungle/sapiens-mod-creation#9]
All of the `availablePlansFor<x>Objects` should be exposed. Additionally, please expose the local data where you define per-asset things. 

For example:

```lua
local huntPlanInfosByObjectType = {
    [gameObject.types.chicken.index] = basicHuntingInfo,
    [gameObject.types.alpaca.index] = spearHuntingInfo,
    [gameObject.types.mammoth.index] = spearHuntingInfo
}
```

This needs to be exposed so I can add my custom mob here.

**Comment by mjdave** [comment]
fixed in b20
